version: "3.9"

services:
  emfcars_database:
    image: postgres
    container_name: db_emfcars_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=emfcars_database
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_emfcars_api
    volumes:
      - .:/usr/app
    depends_on:
      - emfcars_database
    networks:
      - emfcars_database

volumes:
  pgdata:
    driver: local

networks:
  emfcars_database:
    driver: bridge
